spring.application.name=SyncSpace Backend
server.port=8081

# MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/syncspace?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=username_here
spring.datasource.password=password_here
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Gemini / Vertex AI
gemini.api.key=your_key here
gemini.api.base=${GEMINI_API_BASE:https://generativelanguage.googleapis.com}
gemini.model.pm=${GEMINI_PM_MODEL:models/gemini-1.5-flash-latest}
gemini.model.worker=${GEMINI_WORKER_MODEL:models/gemini-1.5-flash-latest}
spring.ai.model.vertexai.enabled=false

# Firebase
firebase.config.path=""


spring.security.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
